# -*- coding: utf-8 -*-
"""xyzzz.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Iq21D5DVEZpr3DOHb0XCDeH4kZRNhrwo
"""


# Data manipulation
import pandas as pd
import numpy as np

# Machine Learning
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.multioutput import MultiOutputClassifier
from sklearn.metrics import classification_report
from xgboost import XGBClassifier



df = pd.read_csv(r"C:\Users\viraj\Downloads\MahiProject\flask app\synthetic_investment_dataset_30k.csv")

print("Shape of dataset:", df.shape)
print("\nColumn names:\n", df.columns.tolist())
df.head()

# ✅ 1. USER INPUT FEATURES (directly entered by user)
user_input_features = [
    'Age',
    'Gender',
    'Education Level',
    'Income',
    'Investment Amount',
    'Financial Knowledge',
    'Risk Tolerance',
    'Investment Horizon'
]

# 🎯 2. TARGETS (what we want the model to predict)
target_columns = [
    'Stocks (%)',
    'Bonds (%)',
    'Gold (%)',
    'Real Estate (%)'
]

# 🧠 3. CALCULATED FEATURES (derived from user input using functions)
calculated_features = [
    'Debt-to-Income Ratio',
    'Net Worth',
    'Occupation',
    'Savings_Rate',
    'Risk_Adjusted_Net_Worth'
]
# 🔄 All model input features = user inputs + calculated
model_features = user_input_features + calculated_features
# 1️⃣ User Input Features (manually entered)
user_input_features = [
    'Age',
    'Gender',
    'Education Level',
    'Income',
    'Investment Amount',
    'Financial Knowledge',
    'Risk Tolerance',
    'Investment Horizon'
]

# 2️⃣ Target columns (what the model predicts)
target_columns = [
    'Stocks (%)',
    'Bonds (%)',
    'Gold (%)',
    'Real Estate (%)'
]

# 3️⃣ Calculated Features (engineered from user input)
calculated_features = [
    'Debt-to-Income Ratio',
    'Net Worth',
    'Occupation',
    'Savings_Rate',
    'Risk_Adjusted_Net_Worth'
]

# 4️⃣ Final model input features (combined)
model_features = user_input_features + calculated_features

# 5️⃣ Filter dataset to keep only necessary columns and add missing columns
columns_to_keep = user_input_features + calculated_features + target_columns

# ✅ Add missing columns with default value of 0
for col in columns_to_keep:
    if col not in df.columns:
        df[col] = 0  # or any other appropriate default value

df = df[columns_to_keep].dropna()

# 🔍 Preview
print("Final model features:", model_features)
print("\nTarget columns:", target_columns)
df.head()
# ✅ Drop all rows with missing values (for now)
df = df[user_input_features + calculated_features + target_columns].dropna()

print("Input features used in model:")
print(model_features)
print("\nTarget columns:")
print(target_columns)

def enrich_user_input(user_input):
    """
    Takes a dictionary of 8 user inputs and calculates engineered features.
    Returns a pandas DataFrame with one row for model prediction.
    """
    data = user_input.copy()

    # Basic values
    income = data['Income']
    investment = data['Investment Amount']

    # 1. Debt-to-Income Ratio
    data['Debt-to-Income Ratio'] = round(investment / (income + 1e-6), 2)

    # 2. Net Worth (Income * 4.5 + Investment)
    data['Net Worth'] = round((income * 4.5) + investment, 2)

    # 3. Occupation (derived from education level and income)
    if data['Education Level'] in ['Post-Graduate', 'Doctorate']:
        data['Occupation'] = 'Professional' if income > 100000 else 'Researcher'
    elif data['Education Level'] == 'Graduate':
        data['Occupation'] = 'Engineer' if income > 70000 else 'Technician'
    else:
        data['Occupation'] = 'Clerk'

    # 4. Savings Rate = Net Worth / Income
    data['Savings_Rate'] = round(data['Net Worth'] / (income + 1e-6), 2)

    # 5. Risk-Adjusted Net Worth
    data['Risk_Adjusted_Net_Worth'] = round(data['Net Worth'] * (1 - (data['Risk Tolerance'] / 10)), 2)

    # Convert to DataFrame with 1 row
    return pd.DataFrame([data])

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from xgboost import XGBClassifier
from sklearn.multioutput import MultiOutputClassifier

# 1️⃣ Split features
categorical_features = ['Gender', 'Education Level', 'Investment Horizon', 'Occupation']
numerical_features = [f for f in model_features if f not in categorical_features]

# 2️⃣ Define transformers
categorical_transformer = OneHotEncoder(handle_unknown='ignore')
numerical_transformer = StandardScaler()

# 3️⃣ ColumnTransformer to apply transformations
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ]
)

# 4️⃣ Final pipeline: preprocessing + model
model_pipeline = Pipeline(steps=[
    ('preprocessing', preprocessor),
    ('model', MultiOutputClassifier(XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=5, random_state=42)))
])

import numpy as np

# Step 1: Define bins and labels
bins = [0, 25, 50, 75, 100]
labels = ['Low', 'Medium', 'High', 'Very High']

# Step 2: Apply binning to each target column
target_columns = ['Stocks (%)', 'Bonds (%)', 'Gold (%)', 'Real Estate (%)']
target_class_columns = [col + "_Class" for col in target_columns]

for col in target_columns:
    df[col + "_Class"] = pd.cut(df[col], bins=bins, labels=labels, include_lowest=True,right=False)

# Step 3: Define label -> numeric mapping
label_mapping = {'Low': 0, 'Medium': 1, 'High': 2, 'Very High': 3}

# Step 4: Strip & convert to string first, then map
# Change: Use the original col for mapping
for col in target_class_columns:
    df[col] = df[col].astype(str).str.strip().map(label_mapping)

# Step 5: Drop rows where mapping failed
df.dropna(subset=target_class_columns, inplace=True)

# ✅ Final check
print("All NaNs removed from mapped class columns:")
print(df[target_class_columns].isnull().sum())

df_classification = df.drop(columns=target_columns)

X = df_classification[model_features]
y = df_classification[target_class_columns]

from sklearn.model_selection import train_test_split

# First, split into Train (70%) and Temp (30%)
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42)

# Further split Temp (30%) into Validation (15%) and Test (15%)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

# Print dataset sizes
print(f"Training Set: {X_train.shape}")
print(f"Validation Set: {X_val.shape}")
print(f"Testing Set: {X_test.shape}")

from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from xgboost import XGBClassifier
from sklearn.multioutput import MultiOutputClassifier

# Define categorical and numerical features again
categorical_features = ['Gender', 'Education Level', 'Investment Horizon', 'Occupation']
numerical_features = [f for f in model_features if f not in categorical_features]

# Preprocessing steps
categorical_transformer = OneHotEncoder(handle_unknown='ignore')
numerical_transformer = StandardScaler()

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ]
)

# Define classifier pipeline
classifier_pipeline = Pipeline(steps=[
    ('preprocessing', preprocessor),
    ('classifier', MultiOutputClassifier(XGBClassifier(
        objective='multi:softmax',  # required for multiclass
        num_class=4,  # because we have 4 classes (Low, Medium, High, Very High)
        eval_metric='mlogloss',
        n_estimators=100,
        learning_rate=0.01,
        max_depth=3,
        random_state=42
    )))
])

# Use the new class target columns
classifier_pipeline.fit(X_train, y_train)

reverse_mapping = {v: k for k, v in label_mapping.items()}

from sklearn.metrics import classification_report, accuracy_score
import numpy as np
import pandas as pd

# Predict on validation set
y_val_pred_raw = classifier_pipeline.predict(X_val)

# Convert to DataFrame with the same column names as y_val
y_val_pred = pd.DataFrame(y_val_pred_raw, columns=target_class_columns)

# Loop through each target class column and print classification report
print("📊 Validation Set Classification Reports:\n")
for col in target_class_columns:
    print(f"--- {col} ---")
    print(classification_report(y_val[col], y_val_pred[col]))
    print()



import joblib

joblib.dump(classifier_pipeline, 'model.pkl')  # Saves to model.pkl
import joblib

joblib.dump(classifier_pipeline, 'model1_allocation.pkl')
print("✅ Model saved as model1_allocation.pkl")
